version: "3.7"

services:
  # This is used to run the built container from docker hub
  # blog_api:
  #   image: kevcoxe/go-blog-api
  #   container_name: go_blog_api
  #   restart: always
  #   environment:
  #     - PORT=5000
  #   expose:
  #     - 5000
  #   ports:
  #     - "5000:5000"

  # This is used to run and build the container that is local
  blog_api_local:
    build: ./blog-api
    container_name: go_blog_api_local
    restart: always
    environment:
      - PORT=5000
    expose:
      - 5000
    ports:
      - "5000:5000"

