server {

    listen 80;

    root /var/www/html/build;

    # Core React application
    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* /(api) {
        include uwsgi_params;
        proxy_pass http://blog_api_local:5000;
    }

}
